### ISSUE TITLE
put does not work without metadata

### ISSUE THREAD

**Issue by azu** [markusahlstrand/cloudflare-kv-storage-rest#2]
`put` implementation does not work correctly.

https://github.com/markusahlstrand/cloudflare-kv-storage-rest/blob/e11e0e37d27b1b9acc08e09b0934216782061548/src/index.js#L128-L139

[Write key-value pair with metadata](https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair-with-metadata) always require `metadata` value.

I have received following response when `put("key", "value")` without metadata.

```json
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10047,
      "message": "multipart put request does not contain required form field 'metadata': '%!s(\u003cnil\u003e)'"
    }
  ],
  "messages": []
}
```

So, I think that the following conditional logic is required.

```js
  async put(key, value, options = {}) {
    const { expiration, expirationTtl, metadata } = options;

    const url = this.getUrlForKey(key);
    const searchParams = new URLSearchParams();

    if (expiration) {
      searchParams.append('expiration', expiration);
    } else if (expirationTtl) {
      searchParams.append('expiration_ttl', expirationTtl);
    }

    const headers = {
      'X-Auth-Email': this.authEmail,
      'X-Auth-Key': this.authKey,
    };

    url.search = searchParams.toString();

    if (!metadata) {
      // https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair
      // eslint-disable-next-line no-undef
      const response = await this.fetch(url.toString(), {
        method: "PUT",
        headers: { ...headers },
        body: value
      });
      return response.ok;
    } else {
      // https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair-with-metadata
      // eslint-disable-next-line no-undef
      const formData = new this.FormData();
      formData.append("value", value);
      formData.append("metadata", JSON.stringify(metadata));
      // eslint-disable-next-line no-undef
      const response = await this.fetch(url.toString(), {
        method: "PUT",
        headers: { ...formData.getHeaders(), ...headers },
        body: formData
      });
      return response.ok;
    }
  }
```

**Comment by markusahlstrand** [comment]
Published version 1.0.2 in npm with your fix for this issue. Also reduced the size of the package, which I hope didn't break anything..

**Comment by markusahlstrand** [comment]
Interesting :) My code that used this npm-lib stopped working after the update, because I was using https://www.npmjs.com/package/formdata-node instead of https://www.npmjs.com/package/form-data. Looks like form-data is a more complete implementation and after switching it works fine.

**Comment by azu** [comment]
Thanks for the quick response!
[My module](https://github.com/azu/express-session-cloudflare-kv) works fine after updating.
